
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";

import { Roboto } from 'next/font/google';

const roboto = Roboto({
  subsets: ['latin'],
  variable: '--font-roboto',
  display: 'swap',
});
export const metadata = {
  title: "Hecht-UI-clone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"
     className="hydrated">
      <body >
        {children}
      </body>
    </html>
  );
}
